# Generated by Django 3.2.18 on 2023-03-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagrecipe',
            old_name='ingredient',
            new_name='tag',
        ),
    ]
