# Generated by Django 3.2.18 on 2023-03-30 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20230330_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Favorite',
        ),
    ]
